import { fileURLToPath } from 'node:url';

import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig, searchForWorkspaceRoot, type Plugin } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

import { getBuildIdentity } from '../../tools/release/build-identity.mjs';

const workspaceRoot = searchForWorkspaceRoot(process.cwd());
const { productVersion, buildRevision } = getBuildIdentity();

function normalizeBase(value: string): string {
  const leading = value.startsWith('/') ? value : `/${value}`;
  return leading.endsWith('/') ? leading : `${leading}/`;
}

const base = normalizeBase(process.env.POSEIDON_BASE_PATH ?? '/');

/**
 * A service worker from a production build, `npm run preview`, the PWA probes or
 * an installed PWA keeps control of its origin, so it will happily serve its
 * precached production bundle on top of the development server. The symptom is
 * silent: no console error, no development badge, no `?mock=` handling and
 * source edits that never appear, because development code is never fetched.
 *
 * Application code cannot fix this, because the stale worker prevents that code
 * from ever loading. Only the server can. Browsers re-fetch the worker script
 * over the network on navigation, so the development server answers that fetch
 * with a worker that clears the caches, unregisters itself and reloads the open
 * tabs onto the real development server.
 *
 * `apply: 'serve'` keeps this out of every build; production still ships the
 * real precaching worker generated by VitePWA.
 */
function developmentServiceWorkerReset(swPath: string): Plugin {
  const source = `
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) await caches.delete(key);
      await self.registration.unregister();
      for (const client of await self.clients.matchAll({ type: 'window' })) {
        client.navigate(client.url);
      }
    })(),
  );
});
`;

  return {
    name: 'poseidon-development-service-worker-reset',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        if (request.url?.split('?')[0] !== swPath) return next();
        response.setHeader('Content-Type', 'text/javascript');
        response.setHeader('Cache-Control', 'no-store');
        response.end(source);
      });
    },
  };
}

export default defineConfig({
  base,
  define: {
    __POSEIDON_VERSION__: JSON.stringify(productVersion),
    __POSEIDON_BUILD_SHA__: JSON.stringify(buildRevision),
  },
  plugins: [
    developmentServiceWorkerReset(`${base}sw.js`),
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'prompt',
      // Core logging and browsing must survive a cold start with no network,
      // so the shell, the content pack and the thumb/gallery creature
      // variants used by dense grids are precached. `hero.webp` is the
      // largest variant (up to 700 KiB each) and is only needed for a
      // creature's own Detail view, so it is cached on first view instead
      // of bloating every cold install/update with every hero image.
      workbox: {
        globPatterns: ['**/*.{js,css,html,webp,png,svg,woff2}'],
        globIgnores: ['**/assets/creatures/*/hero.webp'],
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.pathname.endsWith('/hero.webp'),
            handler: 'CacheFirst',
            options: {
              cacheName: 'poseidon-creature-hero',
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 60 * 60 * 24 * 365,
              },
            },
          },
        ],
      },
      manifest: {
        id: '/',
        name: 'Poseidon',
        short_name: 'Poseidon',
        description: 'A beautiful personal atlas of your underwater life.',
        start_url: `${base}#/`,
        scope: base,
        display: 'standalone',
        background_color: '#F3FAFA',
        theme_color: '#F3FAFA',
        icons: [
          {
            src: `${base}icons/icon-192.png`,
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: `${base}icons/icon-512.png`,
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: `${base}icons/icon-maskable-512.png`,
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      '@poseidon/domain': fileURLToPath(
        new URL('../../packages/domain/src/index.ts', import.meta.url),
      ),
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    fs: { allow: [workspaceRoot] },
  },
});
